blank_issues_enabled: false
contact_links:
  - name: Keine passende Vorlage gefunden?
    url: https://kippebloggt.de/kontakt/
    about: Wenn du keine passende Vorlage für dein Anliegen gefunden hast, kannst du uns einfach direkt eine Nachricht zukommen lassen.
